### PR TITLE
Add CMIP6 collection examples

### PR DESCRIPTION
**Pull request by andersy005**
Towards #5 

- [x] Pangeo CMIP6
- [x] Glade CMIP6

### CODE REVIEW

**Comment by andersy005** [comment]
@rabernat, when you get time, can you take a look at these two examples?

**Comment by rabernat** [comment]
Awesome work! A few comments.

In the csv file, there are fields that are not covered by the spec 
```
activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,path,direct_access,resource_type,data_format
AerChemMIP,BCC,BCC-ESM1,ssp370,r1i1p1f1,Amon,pr,gn,gs://cmip6/AerChemMIP/BCC/BCC-ESM1/ssp370/r1i1p1f1/Amon/pr/gn/,True,gs,zarr
```

The last four columns are `path,direct_access,resource_type,data_format`. What are `direct_access` and `resource_type`? We either need to remove these from the csv or add them to the collection spec somehow. I would say that `data_format` is also unnecessary for these, since they all have the same format and thus can be described with `"format": "zarr"` in the json file. 

More generally, should the csv be allowed to have columns that are not defined in the json file? I would vote no. Columns need to be either attributes or part of the asset definition.

I would also favor just trimming a few lines out of the CSV files and adding them directly to the `collection-spec/examples` directory. That way the examples are self contained. We are not trying to store the *actual catalogs* here.

**Comment by andersy005** [comment]
> The last four columns are path,direct_access,resource_type,data_format. What are direct_access and resource_type? We either need to remove these from the csv or add them to

We don't need these columns (`direct_access`, `resource_type`) anymore. These attributes used to be harvested during the collection build stage. `resource_type` was used to inform intake-esm on how to list files/stores residing in a particular storage resource (posix, gs, s3, hpss tape). `direct_access` was used to tell intake-esm whether the data was directly accessible or not. For the most part, this feature was useful when loading some data assets residing on cold storage such as HPSS tapes (some CESM1 data reside there). This doesn't apply to CMIP data holdings.  I am in favor of removing these two attributes for the time being.

**Comment by andersy005** [comment]
> More generally, should the csv be allowed to have columns that are not defined in the json file? I would vote no. Columns need to be either attributes or part of the asset definition.

I concur 

> I would also favor just trimming a few lines out of the CSV files and adding them directly to the collection-spec/examples directory. That way the examples are self contained. We are not trying to store the actual catalogs here.

👍

**Comment by andersy005** [comment]
@rabernat 

The examples are now self-contained. I replaced the `format_column_name` with `format` in the json files. 

If everything looks good to you, feel free to merge this.

**Pull request merged**
